# Generated by Django 4.2.15 on 2024-08-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_fighter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fighter_photos/'),
        ),
    ]
