# Generated by Django 4.2.15 on 2024-08-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fighter_description_fighter_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='career_highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='reach',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='stance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
