# Generated by Django 4.2.15 on 2024-08-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fighter_age_fighter_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
