# Generated by Django 4.2.15 on 2024-08-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_fighter_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='reach',
            new_name='hometown',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='stance',
        ),
        migrations.AddField(
            model_name='fighter',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
