# Generated by Django 4.2.15 on 2024-08-23 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_event_alter_fighter_hometown_alter_fighter_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='myapp.match'),
        ),
    ]
