# Generated by Django 4.2.15 on 2024-08-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_vote_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
