# Generated by Django 4.2.15 on 2024-08-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_fighter_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='hometown',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
